### ISSUE TITLE
Slowness as you continue to develop

### ISSUE THREAD

**Issue by dumbguy5689** [testdouble/feedback#11]
Hi

  Using Lineman JS, Angular JS, Typescript, Livereload, etc.  As the day goes the build takes longer and longer, and the changes take longer to reload, and our computers memory usage creeps up close to 100%.  Anyone else had these issues with this framework?

**Comment by searls** [comment]
Hey @dumbguy5689, thanks for posting this. We have seen some very-very large Lineman apps become slow on the uptake, and I imagine that sensation would be exacerbated when using LiveReload (because the delay becomes visceral).

@davemo, you've used grunt-newer to tame this. Any examples online?

**Comment by davemo** [comment]
Hi @dumbguy5689, a while back I used Lineman on a pretty large project and made some alterations to the way watching worked as well as utilized grunt-newer. This discussion thread should provide some help if you're interested in trying to make the same optimizations.

https://github.com/linemanjs/lineman/issues/185

I'm going to try and dig up my actual configuration to give you a more concrete example to go from in the meantime.

**Comment by davemo** [comment]
Following up, I couldn't find my other configuration but I did manage to find this in the lineman repo history @dumbguy5689: https://github.com/linemanjs/lineman/compare/grunt-newer-integration

**Comment by davemo** [comment]
Oh, found one more relevant thread! https://github.com/linemanjs/lineman/issues/142

**Comment by davemo** [comment]
Aaand found my relevant config + the watcher in its entirety: https://gist.github.com/davemo/7259064

**Comment by davemo** [comment]
One interesting thing we did in addition to `grunt-newer` and the custom watcher was use `grunt-parallel` in the `dist` phase to speed up some tasks that could be run concurrently:

https://gist.github.com/davemo/7259064#file-config-coffee-L200-L206

``` coffeescript
parallel:
    minification:
      tasks: [
        { cmd: './node_modules/lineman/cli.js', args: ['grunt', 'uglify:admin'] }
        { cmd: './node_modules/lineman/cli.js', args: ['grunt', 'uglify:vendor'] }
        { cmd: './node_modules/lineman/cli.js', args: ['grunt', 'cssmin:admin'] }
      ]
```

**Comment by dumbguy5689** [comment]
@davemo Thanks for taking the time to look those items up, I'll be going through them shortly.
