### ISSUE TITLE
Need to set cloundfront permissions during ember-cli cloudfront deploy

### ISSUE THREAD

**Issue by Dhaulagiri** [testdouble/feedback#12]
Following the [tutorial](http://blog.testdouble.com/posts/2015-11-03-deploying-ember-to-aws-cloudfront-using-ember-cli-deploy.html), I found that I also had to grant the `CloudFrontFullAccess` policy to my user in IAM to deploy to cloudfront.

`- AccessDenied: ... is not authorized to perform: cloudfront:CreateInvalidation`

**Comment by searls** [comment]
paging @kpfefferle

**Comment by Dhaulagiri** [comment]
Feedback is also that the tutorials in combo with the ember-cli-deploy pack was :100:.  Would do again.

**Comment by kpfefferle** [comment]
Thanks for pointing this out @Dhaulagiri! I had noted this permission change in my [personal cheat sheet](http://kevin.pfefferle.co/2015/11/14/deploying-ember-to-aws-cheat-sheet/), but I forgot to go back and add it to these posts.
