### ISSUE TITLE
Ember Cloudfront deployment SSL

### ISSUE THREAD

**Issue by robkinyon** [testdouble/feedback#13]
With the release of ACM (AWS Certificate Manager), your article should be pointing at that as the default method instead of a custom certificate. ACM doesn't cost anything for the certificate (vs. all other providers) and doesn't require the user to manage the certificate out of band. Everything is "just handled" within AWS's infrastructure and using AWS's user management.

The certificates also auto-renew. For free.

**Comment by searls** [comment]
cc / @kpfefferle

**Comment by kpfefferle** [comment]
@robkinyon: Good call. ACM was released shortly after I put this guide together. I may try it out this weekend and update the post accordingly :+1:

**Comment by robkinyon** [comment]
If you have any questions, please hit me up. I *just* finished writing up the ruby scripting that invokes the APIs for this for one of our Angular apps. (S3, Cloudfront, ACM, and Route53).

**Comment by kpfefferle** [comment]
@searls This can be closed now. Blog post has been updated: https://github.com/testdouble/double-takes/pull/59
