### ISSUE TITLE
JMockit or JMock?

### ISSUE THREAD

**Issue by bbasata** [testdouble/feedback#14]
Hello!

In [Post \#50](http://blog.testdouble.com/posts/2016-03-13-testdouble-vs-sinon.html), I read "JMockit's abstractions overwhelmed all but the most ardent experts in isolation testing." My guess, from knowing @searls a bit too well :), is that this meant to refer to JMock and not JMockit. Is this the case?

**Comment by searls** [comment]
Ugh thanks Baraa. IIl fix this in the morning

**Comment by searls** [comment]
Fixed!
