### ISSUE TITLE
Too difficult to find comments on posts

### ISSUE THREAD

**Issue by colinhunt** [testdouble/feedback#15]
I think it's asking a lot of your readers to dig through a github issue tracker just to find comments about a blog post. I expected footer comments or at least a link.

**Comment by searls** [comment]
The truth is that we're interested from hearing about folks, but we're not interested in hosting a discussion forum. We love engaging with readers here, on Twitter, seeing blog responses, etc., but what we don't want is to either: (a) distract from the message of our content to the majority of readers by inviting dissent, derailment, and argument or (b) be in the position of moderating that discussion from the self-interested position of promoting our brand and siding with the content as it is. 

That's the best argument I can give by phone right now, but if that doesn't answer your concern, I'm happy to delve in further later on.

**Comment by colinhunt** [comment]
I see. That is understandable if regrettable. The discussion generated from an article can be even more valuable than the piece itself. But the cost can be quite high. Thanks for your answer. 

Colin
