### ISSUE TITLE
Feedback: Healthy migration habits#Using ActiveRecord models safely

### ISSUE THREAD

**Issue by PragTob** [testdouble/feedback#16]
http://blog.testdouble.com/posts/2014-11-04-healthy-migration-habits.html

For the part "Using ActiveRecord models safely" I'm rather convinced that it is not necessary to give models a new name and set the table_name (although I've seen that advice over and over again).

If the class is defined inside the migration class, then the class will be a different class than the original class as it is name spaced. As constant lookup works from the inside out the code in the migration should reference the "internally defined" class.

E.g. instead of:

```ruby
class SplitUserNameFields < ActiveRecord::Migration
  class MigrationUser < ActiveRecord::Base
    self.table_name = :users
  end
  #...
end
```

I believe it is reasonably save to do:

```ruby
class SplitUserNameFields < ActiveRecord::Migration
  class User < ActiveRecord::Base
  end
  #...
end
```

Small demonstration (role_names is defined on the real role class):

```
[3] pry(main)> class A
[3] pry(main)*   class Role < ActiveRecord::Base
[3] pry(main)*   end  
[3] pry(main)*   def mine
[3] pry(main)*     Role.role_names #should raise
[3] pry(main)*   end  
[3] pry(main)*   def theirs
[3] pry(main)*     ::Role.role_names
[3] pry(main)*   end  
[3] pry(main)* end  
=> :theirs
[4] pry(main)> A.new.theirs
=> ["all", "the", "roles", "in", "my", "project"]
[5] pry(main)> A.new.mine
NoMethodError: undefined method `role_names' for #<Class:0x0000000ed272e8>
from /home/tobi/.rvm/gems/ruby-2.2.3@liefery-backend/gems/activerecord-4.2.5.2/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
```

If I'm wrong, I'd love to know why/how? :) Imo this saves some hassle when doing proper migrations.

Cheers,
Tobi

**Comment by searls** [comment]
Nope, you're absolutely right and in practice this is how I usually do it too, because I have the added safety of the [good_migrations](https://github.com/testdouble/good-migrations) gem.

I didn't want to publish it this way, however, because it can be somewhat easy to write code that'll mess up the scoping and find yourself accidentally tripping Rails auto-loading of a model and then using it.

**Comment by PragTob** [comment]
@searls thanks for the quick answer and clarification :)
