### ISSUE TITLE
minitest-rails in gemfile doesn't load minitest

### ISSUE THREAD

**Issue by sj26** [testdouble/feedback#2]
From [Arcane knowledge needed to write a test](http://blog.testdouble.com/posts/2015-02-16-arcane-knowledge.html):

> For a new Rails project, the "minitest" gem is included even though it's absent from the generated Gemfile.

minitest is a standard library gem, it doesn't need to be in the bundler gemfile.

> In spite of minitest's aforementioned inclusion, the addition of the minitest-rails gem is apparently necessary to avoid some tests from raising errors

minitest-rails adds some niceties but was mainly required back when rails was test-unit only. All it does now is make the relationship more specific to minitest instead of the test unit shim. It also makes using minitest-spec easier, despite tenderlove's best efforts to get minitest-spec explicitly supported by core rails being vetoed. This ties into many later points you make about minitest-spec requiring some trickery, because it does, but it makes sense when you understand how minitest and -spec work.

> The minitest-rails gem must be added to the :development group (in addition to :test) of the Gemfile, so that its rake tasks are available from the command line. That means that running an app in development unnecessarily pollutes it with all the class loading and monkey-patching of its test-scope dependencies

Actually, `gem "minitest-rails"` will load https://github.com/blowmage/minitest-rails/blob/master/lib/minitest-rails.rb which loads only https://github.com/blowmage/minitest-rails/blob/master/lib/minitest/rails/version.rb and https://github.com/blowmage/minitest-rails/blob/master/lib/minitest/rails/railtie.rb which says that certain stuff needs to be loaded when rake tasks are being defined, then they only load minitest when you actually run the test rake tasks.

**Comment by jasonkarns** [comment]
> minitest is a standard library gem

good point. this happened in 1.9.3, or so, right?


Thanks for the feedback!
