### ISSUE TITLE
WIN10: node server.js cmd: no such file or directory

### ISSUE THREAD

**Issue by netchkin** [testdouble/feedback#22]
When I follow the [guide](http://blog.testdouble.com/posts/2016-01-21-isomorphic-clojurescript.html), the first step works flawlessly (downloaded express, created hello world app and run it). However, as soon as I proceed to the next step and add react, upon running the server.js the following error occurs:
```
>node resources/public/js/server-side/server.js
fs.js:634 return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                         ^

eact.inc.js'T: no such file or directory, open 'C:\dev\my\testingcljs\reag2\demo\resourcespublicjsserver-side
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.nodeGlobalRequire (C:\dev\my\testingcljs\reag2\demo\resources\public\js\server-side\goog\bootstrap\nodejs.js:85:26)
    at Object.cljs$core$load_file [as load_file] (C:\dev\my\testingcljs\reag2\demo\resources\public\js\server-side\cljs\core.js:335:13)
    at Object.<anonymous> (C:\dev\my\testingcljs\reag2\demo\resources\public\js\server-side\reagent\impl\util.js:4:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```
The same issue happens when I clone this repository. It even happens if I update react, cljs and lein to latest versions.

I think it has something to do with how windows handles paths, judging from the line  open `C:\dev\my\testingcljs\reag2\demo\resourcespublicjsserver-side` given that the actual path is  open `C:\dev\my\testingcljs\reag2\demo\resources\public\jsserver-side`

EDIT:
I can confirm that the issue prevails with Bash on Windows installed (incl. node 6 and openjdk 7 in the bash)

EDIT2:
I have noticed that when cljs compiles to js, probably part of this stuff in reagent: 
```
(ns reagent.impl.util
   (:require [cljsjs.react]
             [reagent.debug :refer-macros [dbg log warn]]
             [reagent.interop :refer-macros [$ $!]]
             [clojure.string :as string]))
``` 
gets compiled as this in js: 
`cljs.core.load_file("resources\public\js\server-side\react.inc.js");` 
the \r in react gets then interpreted as carriage return character, and possibly each \[A-Za-z] sequence  gets evaluated as an escape sequence, which is the root of the problem...

EDIT3:
found this related issue: http://dev.clojure.org/jira/browse/CLJS-1639

**Comment by netchkin** [comment]
I think that this issue is a clojurescript compiler related one, will pursue it there. closing.

**Comment by andrewvida** [comment]
@netchkin Thank you for reading my post!  I'm glad it has helped and I hope you resolve the issue you're experiencing quickly.  If there's anything I can do to help you on your CLJ/CLJS journey, please don't hesitate to reach out!
