### ISSUE TITLE
Feedback on: Do we need dependency injection in Ruby?

### ISSUE THREAD

**Issue by bhserna** [testdouble/feedback#26]
Hi =)

I like your post =) and I just wanted to add two things about the post, that maybe can be of your interest...

1. Another reason of why dependency injection is good....
2. Another way to write the test...

### 1. Another reason of why dependency injection is good...

I think dependency injection is good because, it protects you or your class, from changes in the dependency...

For example, in your `Shirt` object, you need a `Purchaser` that receives a `product_code`.... But continuing the example, is posible that this `Purchaser` will need to interact with more things that have nothing to do with the `Shirt`, like a payment gateway or a mailer service...

So, if that happen... in your first example you would need to add that knowledge to the `Shirt` object....

```ruby
# first example
class Shirt
  def initialize(product_code)
    @product_code = product_code
  end

  def buy!
    if Inventory.check_availability(product_code)
      purchaser = Purchaser.new(PaymentGateway, Mailer)
      purchaser.purchase_item(product_code)
      true
    else
      false
    end
  end

  private

  attr_reader :product_code
end
```

....while on your second example, you would not have to change anything in the `Shirt` object, and I think that's good...

```ruby
# second example
class Shirt
  def initialize(product_code, inventory, purchaser)
    @product_code = product_code
    @inventory = inventory
    @purchaser = purchaser
  end

  def buy!
    if inventory.check_availability(product_code)
      purchaser.purchase_item(product_code)
      true
    else
      false
    end
  end

  private

  attr_reader :product_code, :inventory, :purchaser
end

purchaser = Purchaser.new(PaymentGateway, Mailer)
shirt = Shirt.new("1234", Invetory, PaymentGateway)
```

### 2. Another way to write the test...

To write mocks, I normally use a combination of plain explicit roles, as objects, and the most common rspec methods like `allow(x).to receive(y)` and `expect(x).to receive`, but as you are avoiding `allow(x).to receive`... I think you could do something like the next example, to do something more similar to the "Arrange, Act, Assert" pattern that you like (although I am still using `expect(x). to receive`)...

```ruby
require 'rspec'
require_relative 'shirt_v2'

describe Shirt do
  class FakePurchaser
    def self.purchase_item(product_code)
    end
  end

  class FakeInventory
    def initialize(availability:)
      @availability = availability
    end

    def check_availability(product_code)
      @availability
    end
  end

  def inventory_with(args)
    FakeInventory.new(args)
  end

  def purchaser
    FakePurchaser
  end

  describe "doesn't buy shirts when there are none left" do
    attr_reader :shirt

    before do
      inventory = inventory_with(availability: false)
      @shirt = Shirt.new('small', inventory, purchaser)
    end

    it "returns false" do
      result = shirt.buy!
      expect(result).to eq(false)
    end

    it "does not call the purchaser" do
      expect(purchaser).not_to receive(:purchase_item)
      shirt.buy!
    end
  end

  describe "buys a shirt when there are shirts available" do
    attr_reader :shirt

    before do
      inventory = inventory_with(availability: true)
      @shirt = Shirt.new('abc123', inventory, purchaser)
    end

    it "returns true" do
      result = shirt.buy!
      expect(result).to eq(true)
    end

    it "calls the purchaser with the product code" do
      expect(purchaser).to receive(:purchase_item).with("abc123")
      shirt.buy!
    end
  end
end
```

And that's all =)... I hope you can take something useful from this =)

**Comment by kbaribeau** [comment]
Hi @bhserna ! Thanks for the feedback!

I enjoyed your first comment. It's always nice when a design shows that it's robust to some new changes.

I'm not sure I understand your second example. It seems like it accomplishes pretty much the same thing as my tests, but it takes more code to do so. I'm generally going to prefer solutions that use less code if I can get away with it.

If I wanted to avoid using `spy` from rspec mocks I might do something like this...

```
describe Shirt do
  class FakePurchaser
    attr_reader :was_called, :product_code
    def purchase_item(product_code)
      @was_called = true
      @product_code = product_code
    end
  end

  it "doesn't buy shirts when there are none left" do
    fake_inventory = Object.new
    fake_inventory.define_singleton_method(:check_availability) { |_product_code| false }
    fake_purchaser = FakePurchaser.new
    shirt = Shirt.new('small', fake_inventory, fake_purchaser)

    result = shirt.buy!

    expect(result).to eq(false)
    expect(fake_purchaser.was_called).to be_nil
    expect(fake_purchaser.product_code).to be_nil
  end

  it "buys a shirt when there are shirts available" do
    fake_inventory = Object.new
    fake_inventory.define_singleton_method(:check_availability) do |product_code|
      product_code == 'abc123'
    end
    fake_purchaser = FakePurchaser.new
    shirt = Shirt.new('abc123', fake_inventory, fake_purchaser)

    result = shirt.buy!

    expect(result).to eq(true)
    expect(fake_purchaser.was_called).to eq(true)
    expect(fake_purchaser.product_code).to eq('abc123')
  end
end
```

But... `spy` is one of my favourite features in rspec mocks. I think it does a pretty good job of giving me a test double that's clearly understood.

**Comment by bhserna** [comment]
Hey, thanks for reading and answer my comment =)

About my second example... Yes jaja, it suppose to accomplish the same thing, it was just another way to write it =) ...

Personally I was trying to change two things...

1. Express the interface of the objects in a "simpler way" (in my opinion jaja)
2. Separate the assertion for the result and the assertion for message sent to the injected object.

I think that I like to write mocks that way, because for me, is easier to visualize the expected interface, something, like...

```ruby
class FakePurchaser
  def self.purchase_item(code)
  end
end

class FakeInventory
   def self.check_availability(product_code)
   end
end
```

Than to what the de definition "on the fly", like...

```ruby
fake_inventory = Object.new
fake_inventory.define_singleton_method(:check_availability) do |product_code|
  product_code == 'abc123'
end
```

I know that is just ruby, but maybe I just don't use it very much...

But that's it =) ... just another way to write it.
