### ISSUE TITLE
Post #29

### ISSUE THREAD

**Issue by rafaelgonzalez** [testdouble/feedback#3]
Hi,

Sorry I just wanted to send an email to respond to a specific point in [Post #29](http://blog.testdouble.com/posts/2015-02-16-arcane-knowledge.html), so I tried the email at the bottom of the page but got a Mail Delivery Subsystem response:

```
Delivery to the following recipient failed permanently:

     hello@testdouble.com

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the relay mail.gandi.net by mail.gandi.net. [217.70.184.11].

The error that the other server returned was:
535 5.7.8 Error: authentication failed:
 (SMTP AUTH failed with the remote server)
```

Below is the original content of the email:

Hi there,

Just to chime in in response to bullet point #19 of [your article](http://blog.testdouble.com/posts/2015-02-16-arcane-knowledge.html), bundle caching is only available for private repos on Travis. Not sure if you are aware, so I thought I should let you know :)

See the first paragraph here: http://docs.travis-ci.com/user/caching/#Caching-directories-(Bundler%2C-dependencies)

Cheers

**Comment by jasonkarns** [comment]
Thanks!

Not really sure what the issue was with the email, but hopefully it's resolved now. (the address is still live and active)
