### ISSUE TITLE
Re: "My favorite way to TDD"

### ISSUE THREAD

**Issue by atineoSE** [testdouble/feedback#8]
Hi Justin 

I was excited to continue learning from your approach to TDD after having read through your contributing-test wiki. I have watched so far the first part of the 4 part series. 

I have found it to be a very good summary and elaboration on the ideas of the wiki. I think there's tremendous insight into your analysis, something much needed by the community. 

These are my take-home messages (it wouldn't hurt for you to do the same as conclusions for your introduction):
- Discovery testing is a design technique, guided by tests, that promotes clean modular design.
- Though it builds upon classical TDD and software engineering practices outlined in GOOS, it goes beyond that.
- It is based on mocking to achieve its design goals, so don't be afraid to mock.
- The value of such tests as regression suite is only marginal. The true value of the tests is to produce modular "emergent" design organically, just by following the method as opposed to "refactoring your way out of chaos".

What I like the most about your approach is that it seems to be a good fit for half-baked programmers (like me), who are not so smart to get their way out of a mess by ways of refactoring. In my view, refactoring is an art, one that must be learnt through experience and study. Somehow TDD proponents seem to convey that refactoring "just happens". Of course, they don't mean that, but if you don't read close enough, that is the message that comes across. I like to say that one's classical TDD (as per your classification) is only as good as one's refactoring skills. 

In a recent article, Kent Beck elaborated on his method to bring his ideas to be widely adopted (
https://m.facebook.com/notes/kent-beck/idea-to-impact/990860537613477). I am inspired by that article to unashamedly suggest some ideas to encourage you to increase the reach of your technique (pls, forgive me).

Boil the technique down to an elevator pitch. Condense the essence. Find a catchy name. "Discovery Testing" is a good start but it does not convey that it is a DESIGN technique. How about "Discovery Testing Design" (DTD)? You may want to brainstorm it in your circle. The discussion Detroit vs. London is good as background but you already detach yourself from the authors of the London-school. Just don't call yourself London-school like you do in the video then. Be clear about recognizing the schools and putting credit where is due (which you do well) and then don't be ashamed to push Discovery Testing by its name as something related, but that goes beyond. 

My 2 cents.

Adrian Tineo
@atineoSE

P.S: I think Java is a good decision. Most people from my generation learned object-oriented programming with Java. I am looking forward to working through the example in the next episodes of the series. Yai!

**Comment by searls** [comment]
Thanks for the feedback.

**Comment by atineoSE** [comment]
Hi again

I worked now step by step through the remaining episodes. Some aspects became clearer through it, particularly the change in testing mode between collaborator nodes and leaf nodes, and it was good to see it in a realistic scenario with the compilations problems and the occasional hard-to-figure-out impediment.

Particularly interesting was the discussion about the pain of having too much logic in collaborator objects, such as ReplacesWorld. At that point, I agree it was starting to become ugly.

I am not completely sure that I understood your point there completely though. If I got it right, you meant that:
on the positive side, the painstaking work on ReplacesWorld left us with a bunch of value objects that define more clearly the problem domain (and it passes the tests so let's just go ahead and refactor if and when we need to)
on the negative side, it was far too much logic for what a collaborator object (non-leaf node of the hierarchical tree) should typically have in this flavour of TDD, which can adversely affect a nice break down of the problem

Is that an accurate description of the major conclusion to episode 3?

I have struggled at places. Leaving aside my lack of familiarity with Eclipse bag-of-tricks (you use like it you are playing a video game) and my inexperience with Mockito, I particularly struggled with some names. I refer specifically to Contents and Outcome. It was not immediately clear to me what these objects should be like, what instance variables they should contain. I understand that is part of the exercise though: let it be what it wants to be as you descend down the tree. Still, Contents could just have been a Cell with a live boolean attribute. 

In episode 4 though this confusion peaks when you define Point, because at this moment you have Outcome to contain Contents and Points, pushing down Coordinates to Point, which incidentally also has Contents. I totally fail to see the need to create Point then and to me it makes it all so much more complicated. 

This makes me realize a potential problem when creating such objects on demand, as you descend down the tree: responsibilities can get diluted, duplicated, or otherwise fuzzy. Would you agree with that general statement for the technique and/or with this example in particular?

Regards,

Adrian Tineo

**Comment by searls** [comment]
> Is that an accurate description of the major conclusion to episode 3?

Yep, that's about the size of it.

> In episode 4 though this confusion peaks when you define Point, because at this moment you have Outcome to contain Contents and Points, pushing down Coordinates to Point, which incidentally also has Contents. I totally fail to see the need to create Point then and to me it makes it all so much more complicated.

If you view values as just structs, I think "much more complicated" is overblowing it (e.g. if this had been a JSON object or a Ruby hash, it'd just be one more layer of nesting in a broader structure, but since it's Java it's easier to combine the values behind a new named type). One thing I see a bunch of people do in these circumstances is immediately start assembling very complex structures like `Collection<Map<Contents, Collection<Coordinates>>>` which is not only unwieldy to write, but a lot to keep track of in one's head.

**Comment by atineoSE** [comment]
Alright, "much more complicated" is a bit overboard and nested Collections are definitely hard to keep in the head. My concerns is more with the possible problems when applying the technique as you describe it. 
In case of a "fat" collaborator, it looks like we find some of the same symptoms of classical TDD that you were aiming to solve. Or said otherwise, how much can you degrade the spirit of the technique before you end up having the same problems than you'd have if you'd started the classical way?
A missing piece too is what kind of SAFE tests would you add on top to cover for the extra testing that you'd purportedly have had if you had gone the classical way? Care for an episode 5 ;-) ?

**Comment by searls** [comment]
> In case of a "fat" collaborator, it looks like we find some of the same symptoms of classical TDD that you were aiming to solve. Or said otherwise, how much can you degrade the spirit of the technique before you end up having the same problems than you'd have if you'd started the classical way?

That's a great question. I think that it's a personal and contextual enough thing that it's up for everyone to practice for themselves. The metric I use is "am I finding myself needing to refactor the contracts between units a lot? If so then I probably overloaded too many of them with behavior.

> A missing piece too is what kind of SAFE tests would you add on top to cover for the extra testing that you'd purportedly have had if you had gone the classical way? Care for an episode 5 ;-) ?

That's a whole other topic, but in general for a system of this size I'd just write one or two happy path smoke tests that plug the whole thing together in as integrated a way as possible (e.g. invoking everything from the command line and looking at output)
